language: python

python:
  - "2.7"
  
install:
  - pip install .
  
script:
  - ./CID/cid.sh

deploy:
  provider: pypi
  user: $TWINE_USERNAME
  password: $TWINE_PASSWORD
  on:
    branch: production
